version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: node -v
  gate:
     type: approval
  test:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: nove -v
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - hold
      - test
